import{a as w,i as m,S as P}from"./assets/vendor-eded45c0.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))r(s);new MutationObserver(s=>{for(const o of s)if(o.type==="childList")for(const i of o.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&r(i)}).observe(document,{childList:!0,subtree:!0});function a(s){const o={};return s.integrity&&(o.integrity=s.integrity),s.referrerPolicy&&(o.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?o.credentials="include":s.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(s){if(s.ep)return;s.ep=!0;const o=a(s);fetch(s.href,o)}})();const x=document.querySelector(".loader"),q=document.querySelector(".loader2");function c(){x.classList.toggle("visually-hidden")}function d(){q.classList.toggle("visually-hidden")}async function p(t,e){const a="43234755-a337228de2a5121df872aa78d";e.currentPage===1?c():d();const r=await w.get("https://pixabay.com/api/",{params:{key:a,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:e.currentPage}});return e.currentPage+=1,r}function y(t){return t.map(({webformatURL:e,tags:a,largeImageURL:r,likes:s,views:o,comments:i,downloads:S})=>`<li class='card'>
        <a class="gallery-link" href="${r}"><img class='image' src='${e}' alt='${a}'></a>
        <div class='description'>
        <div class='title-text'><h4 class='title'>Likes</h4><p class='text'>${s}</p></div>
        <div class='title-text'><h4 class='title'>Views</h4><p class='text'>${o}</p></div>
        <div class='title-text'><h4 class='title'>Comments</h4><p class='text'>${i}</p></div>
        <div class='title-text'><h4 class='title'>Downloads</h4><p class='text'>${S}</p></div>
        </div>
        </li>`).join("")}const v=document.querySelector(".form"),u=document.querySelector(".searchInput"),n=document.querySelector(".list"),l=document.querySelector(".submitBtn"),h=document.querySelector(".loadMore"),g={currentPage:1};l.disabled=!0;function M(t,e){localStorage.setItem(t,e)}function C(t){const e=localStorage.getItem(t);return e||null}u.addEventListener("input",()=>{u.value.trim()!==""?l.disabled=!1:l.disabled=!0});v.addEventListener("submit",$);h.addEventListener("click",E);async function $(t){t.preventDefault();const e=u.value.trim();if(g.currentPage=1,e!==""){n.innerHTML="",L(),M("searchInputValue",e);try{const a=await p(e,g);if(a.data.hits.length===0)c(),f("Sorry, there are no images matching your search query. Please try again!");else{c(),n.insertAdjacentHTML("beforeend",y(a.data.hits)),I.refresh();const r=Math.ceil(a.data.totalHits/a.config.params.per_page);b(a,r)}v.reset(),l.disabled=!0}catch(a){c(),f(`${a}`)}}}async function E(){L();const t=C("searchInputValue");try{const e=await p(t,g),a=Math.ceil(e.data.totalHits/e.config.params.per_page);d(),n.insertAdjacentHTML("beforeend",y(e.data.hits)),I.refresh(),T(),b(e,a)}catch(e){d(),f(`${e}`)}}function T(){const e=n.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}function f(t){m.error({message:t,position:"topRight",backgroundColor:"#EF4040",messageColor:"#fff",timeout:3e3})}function k(){m.warning({position:"topRight",backgroundColor:"#00A36C",message:"We're sorry, but you've reached the end of search results."})}function A(){h.classList.remove("visually-hidden")}function L(){h.classList.add("visually-hidden")}function b(t,e){const a=t.data.hits.length,r=setInterval(()=>{if([...n.querySelectorAll("img")].every(i=>i.complete))if(clearInterval(r),t.config.params.page>=e)if(a>15)k();else return;else A()},50)}const I=new P(".list a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
